- .github/workflows/codeql-analysis.yml
N/A
Adds CodeQL security analysys
None
None
> Add CodeQL analysys

- .restyled.yaml
- commands/fursona.ts
- index.ts
Closes #32 
Adds a new fursona system for users to use, see #32.
N/A
N/A
> Add fursona system

- .github/workflows/build.yml
- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- package.json
N/A
Adds a GitHub Action to run `tsc`
None
None
> Add TSC CI workflow

- .github/workflows/build.yml
- .gitignore
- .prettierignore
- clean.sh
- commands/markov.ts
- commands/owos.ts
- commands/tildes.ts
- commands/uwus.ts
- index.ts
- package-lock.json
- package.json
- tsconfig.json
N/A
Now, errors show a proper TS-fetched line, based on a generated sourcemap!
None
None
> Add Error SourceMap Support

- index.ts
N/A
CommandLoader and ModuleLoader would error out when loading `.map` files, and this fixes it.
N/A
N/A
> [BUG] Fix UnknownExtensionWarning on sourcemap files

- commands/exec.ts
Closes #43
This PR adds an `~exec` command that will execute code.
- Me having to SSH in to do all commands
N/A
> [FEATURE] Add exec command

- commands/update.ts
N/A
Update all-in-one-chunk instead of sending 6 API requests.
- Spamming the API, but that's bad
In the future, we need to clean up the update command.
> [BUG] Fix update command spamming the API

- index.ts
- package-lock.json
- package.json
N/A
We can now make custom paths to modules for commonly-used classes like Paged Embeds (in the future)
Relative paths: a mess
N/A
> Add module-aliases

- src/commands/hug.ts
Closes #64 
We now delete the command message on `~hug`.
None
None
> [FEATURE] Delete command message on affection command

- package-lock.json
- package.json
- src/commands/cat.ts
- src/commands/dog.ts
- src/commands/koala.ts
- src/commands/meme.ts
N/A
What did you change?
Added a meme command, random cat picture command, random dog picture command and a random koala picture command
All of these commands use an external API.
A clear and concise description of any alternative solutions or features you've considered.
N/A
Add any other context or screenshots about the PR here.
> [FEATURE] Add new commands

- .github/workflows/dependency-inspect.yml
- .gitpod.yml
- tsconfig.json
> Reformat files

- README.md
- src/commands/owos.ts
- src/commands/tildes.ts
- src/commands/uwus.ts
Closes #90 
I added the ===== line and then added the line to mention own users placing, if not in top 10
None
None
> [FEATURE] Added self in uwus/owos/tildes as mentioned in #90

- src/commands/uwuify.ts
Closes #97 
I added {split: true} to the send method in uwuify.js
None
None
> [BUG] Added split option to uwuify (#67)

- src/commands/fox.ts
N/A
Adds a `~fox` command.
None
None
> [FEATURE] Add fox command

- src/commands/cuties.ts
Because im not cute.
N/A
What did you change?
A clear and concise description of any alternative solutions or features you've considered.
Add any other context or screenshots about the PR here.
> feat(cuties): remove Nepgfurmixpro from cuties

- src/commands/owos.ts
- src/commands/tildes.ts
- src/commands/uwus.ts
> refactor: refactor uwus, owos, and tildes

- README.md
- package-lock.json
- package.json
- src/log.ts
Closes #125 
Now we throw the stack trace on errors.
> feat: stack traces in errors

- src/index.ts
Fixes #435
**DRAFT:** Clean up and comment source code.
> refactor: comment out index.ts

- clean.sh
- package-lock.json
- src/index.ts
- src/lib/types/Augments.d.ts
- src/log.ts
- start.sh
N/A
The second-largest set of repository refactors on this bot, ever.
> refactor: the big one

- .vscode/settings.json
- README.md
- src/commands/about.ts
- src/index.ts
- src/log.ts
- start.sh
Closes #464 
Now we get a git ref on startup.
> feat: startsh versioning

- src/commands/update.ts
- src/index.ts
- src/log.ts
Fix a couple issues:
Closes #465
Closes #460
> Mass issue fix

- install.sh
- src/config.rename-me.ts
- src/index.ts
Closes #470
Add an installer script
> feat: add install script

- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- package-lock.json
- package.json
prevents people like @ilikestohack from writing bad commit messages and
@thetayloredman from writing ugly code
Closes #480 
We now use Husky, commitlint, and lint-staged in our pre-commit hooks.
> repo: use Husky, lint-staged, and commitlint to prevent kids like @ilikestohack writing bad code

- .eslintrc.cjs
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- package-lock.json
- src/commands/admin.ts
- src/commands/fursona.ts
- src/commands/help.ts
- src/commands/setprefix.ts
- src/index.ts
- src/lib/Client.ts
- src/lib/CommandHandler.ts
- src/lib/interfaces/commands/CommandConfig.ts
- src/lib/interfaces/db/GuildData.ts
- src/lib/types/Augments.d.ts
- src/lib/utils/doesHavePrefix.ts
N/A
Added a per guild prefix option defaulting to config set prefix
> Add per guild prefixes

- src/commands/admin.ts
- src/config.rename-me.ts
- src/lib/Permissions.ts
- src/lib/getPermissionsForUser.ts
- src/lib/interfaces/Config.ts
N/A
Added a new BOT_SUPER_ADMIN permission level.
Requested by @ilikestohack, my firewall is up so I can afford you having eval.
**ALSO! ISSUE #500! THANK YOU TO DEPENDABOT FOR GETTING US HERE!**
> feat: superadmins feature

- src/commands/admin.ts
- src/commands/fursona.ts
- src/commands/help.ts
- src/commands/info.ts
- src/commands/meme.ts
- src/lib/interfaces/PublicConfig.ts
- src/publicConfig.ts
N/A
Add a ProtoBot official color palette.
not having one - boring
@ilikestohack please review uwu
> feat: add color scheme

- src/commands/admin.ts
- src/utils/onready/status.ts
Fixes #576 
This PR adds a new command: `/admin status` and its subcommands `set` and `reset`.
This has been tested and works successfully.
> feat: add /admin status
